services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./web/html:/var/www/html
      - ./web/php:/usr/local/etc/php
      - ./web/.nodenv-data:/root/.nodenv
    environment:
      COMPOSER_ALLOW_SUPERUSER: 1
      TZ: Asia/Tokyo  # タイムゾーンを設定
    depends_on:
      - db
    links:
      - db
      - phpmyadmin
    networks:
      - lamp

  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    ports:
      - "3306:3306"
    volumes:
      - ./db/.data:/var/lib/mysql  # ホストのディレクトリをマウント
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: default
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      TZ: Asia/Tokyo  # タイムゾーンを設定
    networks:
      - lamp

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    platform: linux/amd64  # プラットフォームを指定
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpassword
      TZ: Asia/Tokyo  # タイムゾーンを設定
    depends_on:
      - db
    networks:
      - lamp

  mailpit:
    image: axllent/mailpit
    ports:
      - "8025:8025"
    networks:
      - lamp

networks:
  lamp:
